# Generated by Django 5.2.16 on 2026-07-19 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, help_text='Optional login handle. Stored as NULL when unset, never as an empty string — the unique index depends on it.', max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('full_name', models.CharField(blank=True, help_text='Canonical display label. Derived from first/last when left blank.', max_length=255)),
                ('primary_phone', models.CharField(blank=True, max_length=32)),
                ('tier', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Deactivate rather than delete, so historical appointments keep a valid provider reference.', max_length=16)),
                ('is_provider', models.BooleanField(default=False, help_text='A provider IS the bookable clinician — there is no separate Provider entity.')),
                ('provider_hours', models.JSONField(blank=True, default=dict, help_text='Weekly working hours KEYED BY LOCATION ID, because the same person can work different days at different sites: {"<location_id>": [{"start_time": "09:00", "end_time": "17:00", "days": ["mon", "tue"]}]}')),
                ('inactivity_timeout', models.PositiveIntegerField(blank=True, help_text='Minutes of inactivity before the session is ended. Falls back to settings.DEFAULT_INACTIVITY_TIMEOUT_MINUTES when unset.', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='Null only for the platform superuser.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location__name'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'status'], name='idx_user_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uniq_user_tenant_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'username'), name='uniq_user_tenant_username'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['tenant', 'user'], name='idx_userlocation_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='uniq_userlocation_user_location'),
        ),
    ]
