# Generated by Django 5.2.16 on 2026-07-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('customer_id', models.CharField(help_text='The Customer ID a user enters at login to resolve this business.', max_length=32, unique=True)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone name. Each location may override it with its own.', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='An inactive tenant is blocked at login rather than mid-call.')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, default='US', max_length=64)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone name. This location's own — appointment and transfer-hours calculations are evaluated in it.", max_length=64)),
                ('phone', models.CharField(blank=True, help_text="The public-facing number for this site. Not the agent inbound number — that lives on the location's AgentSetting row.", max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate rather than delete, so past appointments and call logs stay readable.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='idx_location_tenant_active')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_location_tenant_slug')],
            },
        ),
    ]
