# Generated by Django 4.2.30 on 2026-07-19 11:59

import apps.agents.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, help_text='The master switch for this location. While off, the agent does not answer.')),
                ('voice_provider', models.CharField(choices=[('live', 'Live (realtime speech)'), ('google', 'Google'), ('gemini', 'Gemini')], default='live', max_length=16)),
                ('greeting', models.TextField(blank=True, help_text='Spoken the moment the call connects. Rendered server-side from this text and costs zero LLM tokens, so the caller hears something immediately.')),
                ('prompt_text', models.TextField(blank=True, help_text='The system prompt for this location. Supports {{variable}} placeholders.')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='The {{variable}} substitution map, merged with server-computed runtime values at call setup. Runtime values win on a clash.')),
                ('inbound_phone_number', models.CharField(blank=True, help_text='E.164, e.g. +13125550142. Globally unique across all businesses — it is what routes an inbound call to this location.', max_length=32, null=True, unique=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=64)),
                ('twilio_auth_token', apps.agents.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted at rest and write-only in forms. Never rendered, never logged, never returned by a view.', max_length=512)),
                ('transfer_enabled', models.BooleanField(default=False)),
                ('transfer_phone_number', models.CharField(blank=True, max_length=32)),
                ('transfer_secondary_number', models.CharField(blank=True, help_text='A second destination, e.g. another language or an overflow line.', max_length=32)),
                ('transfer_timezone', models.CharField(default='America/Chicago', help_text='The timezone the transfer windows below are evaluated in.', max_length=100)),
                ('transfer_working_hours', models.JSONField(blank=True, default=dict, help_text='{"monday": {"enabled": true, "start": "09:00", "end": "17:00"}, ...}. Empty means no restriction.')),
                ('transfer_keywords', models.JSONField(blank=True, default=list, help_text='Extra lowercased caller phrases that trigger a handoff. These are ADDED to the runtime built-in set, not a replacement for it.')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Agent setting',
                'ordering': ['location__name'],
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='idx_agentsetting_enabled')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentsetting',
            constraint=models.UniqueConstraint(fields=('tenant', 'location'), name='uniq_agentsetting_tenant_location'),
        ),
    ]
