# Generated by Django 4.2.30 on 2026-07-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('phone_e164', models.CharField(blank=True, db_index=True, help_text='Stored in E.164 form (+13125550142). Normalised on save so a repeat caller matches however the number was typed.', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai_phone', 'AI phone call'), ('manual', 'Added manually'), ('web', 'Web')], db_index=True, default='manual', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['last_name', 'first_name', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'phone_e164'], name='idx_contact_tenant_phone'), models.Index(fields=['tenant', 'last_name', 'first_name'], name='idx_contact_tenant_name')],
            },
        ),
    ]
