# Generated by Django 4.2.30 on 2026-07-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Read aloud by the agent when a caller asks what this involves. Write it the way you would say it, not the way you would print it.')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='How long the appointment itself lasts.')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Extra time held AFTER the appointment — cleaning down, notes, turnaround. The next slot cannot start inside it.')),
                ('requires_resource', models.BooleanField(default=False, help_text='Tick if this service needs a room, chair or piece of equipment. Availability will only offer a slot when a resource is free.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services keep their booking history but are never offered to a caller.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are offered first. Ties fall back to name.')),
                ('location', models.ForeignKey(blank=True, help_text='Leave blank to offer this service at every location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'location', 'is_active'], name='idx_service_tenant_loc_active')],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('resource_number', models.CharField(blank=True, help_text='Whatever your staff actually call it — "3", "B", "Suite 2".', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive resources keep their booking history but are never offered when the agent looks for a free slot.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are offered first. Ties fall back to name.')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'location', 'is_active'], name='idx_resource_tenant_loc_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='uniq_resource_location_name'),
        ),
    ]
