# Generated by Django 4.2.30 on 2026-07-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0002_service_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='scheduled', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai_phone', 'AI phone call'), ('manual', 'Booked manually'), ('web', 'Web')], db_index=True, default='manual', help_text='How this booking came about. Server-stamped, never chosen by a user — it is the provenance record.', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(help_text='PROTECT, not CASCADE: deleting a person must never silently delete the record that they were seen. A contact with bookings is erased in place instead (Contact.anonymize).', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.contact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.location')),
                ('provider', models.ForeignKey(blank=True, help_text='The staff member seeing this contact. Null for a service that needs nobody in particular, such as a phone consultation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.resource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['tenant', 'location', 'start_at'], name='idx_appt_tenant_loc_start'), models.Index(fields=['tenant', 'status'], name='idx_appt_tenant_status'), models.Index(fields=['tenant', 'contact'], name='idx_appt_tenant_contact')],
            },
        ),
    ]
