# Generated by Django 4.2.30 on 2026-07-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('scheduling', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('caller_phone', models.CharField(blank=True, help_text='The number to ring back on, as the caller gave it. Not normalised to E.164 like Contact.phone_e164: nothing looks a callback up by number, and an extension or "ask for Dana" note would be destroyed by normalisation.', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(choices=[('ai_phone', 'AI phone call'), ('manual', 'Added manually'), ('web', 'Web')], default='ai_phone', help_text='How this callback came about. Server-stamped, never a form field — it is the provenance record. Defaults to ai_phone because the agent is the writer that cannot choose.', max_length=32)),
                ('notes', models.TextField(blank=True, help_text="What happened when you rang back. Kept through a contact erasure — it is the queue's working record, not identity.")),
                ('contact', models.ForeignKey(blank=True, help_text='SET_NULL, not PROTECT: a callback is a transient queue item, so it must survive a contact being removed rather than block the removal. Null also means "we never found out who this was" — see caller_name / caller_phone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_requests', to='scheduling.contact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'location', 'status'], name='idx_callback_tenant_loc_status')],
            },
        ),
    ]
