# Generated by Django 4.2.30 on 2026-07-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('scheduling', '0004_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_by_session',
            field=models.ForeignKey(blank=True, help_text='The call that produced this booking — the provenance link behind source=ai_phone, server-stamped by the runtime and never chosen by a user. SET_NULL, not CASCADE: call logs are retention-purged and callers are erased, and neither may take the booking down with them. Plural related_name because one call can book more than one appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to='calls.callsession'),
        ),
    ]
