# Generated by Django 4.2.30 on 2026-07-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0004_callbackrequest'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='agent_phone', help_text='How the call reached the agent. One value in practice — this is an inbound-phone product — but the column exists so a second channel does not need a migration on a table that will be the largest in the database.', max_length=32)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('google', 'Google'), ('gemini', 'Gemini')], default='live', max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('transferred', 'Transferred'), ('failed', 'Failed')], db_index=True, default='in_progress', max_length=16)),
                ('from_number', models.CharField(db_index=True, max_length=32)),
                ('to_number', models.CharField(db_index=True, max_length=32)),
                ('provider_call_sid', models.CharField(help_text='The Twilio CallSid. UNIQUE because it is the idempotency key for webhook redelivery: Twilio retries, and the constraint is what stops a retry minting a second session for one call.', max_length=64, unique=True)),
                ('transcript', models.JSONField(default=list, help_text='[{sequence, role, text, at, offset}] — the turns, in order. PII: never logged, never emitted at INFO.')),
                ('logs', models.JSONField(default=list, help_text='[{sequence, level, category, title, raw_json, occurred_at}] — the event log. Tool-call arguments are redacted BEFORE they are persisted here; a create_contact payload is a full name and a date of birth.')),
                ('analysis', models.JSONField(default=dict, help_text='{summary, success_evaluation, extracted_data}. Legitimately empty on an abandoned or failed call — nothing happened to analyse, so every reader must render {} without falling over.')),
                ('usage', models.JSONField(default=list, help_text='[{turn_sequence, cost_breakdown, cost_usd}] — per-turn cost. Cost is derived from this list at read time, never stored as a column, so a corrected rate card re-prices history.')),
                ('transfer', models.JSONField(default=dict, help_text='{result, reason, destination, initiated_at, duration_seconds}. Shape fixed by the shipped partials/_transfer_outcome.html. Empty dict = no transfer was ever attempted, which is the common case — most callers never ask for a human.')),
                ('waveform_peaks', models.JSONField(blank=True, help_text='{caller, bot, bins} for the call-detail waveform. NULL rather than empty-by-default: absent means "never computed", which is not the same as a recording that is genuinely silent.', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Call-level detail that needs no column of its own — including the recording consent basis and its retention window, which live on the row that was actually recorded because the policy that applies is the policy at the time of the call.')),
                ('recording_blob', models.CharField(blank=True, default='', help_text='PRIVATE storage path; "" = no recording. Served only through a short-lived signed URL — never rendered as a src against a public media path.', max_length=512)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, help_text='SET_NULL, not PROTECT and never CASCADE: an unknown or withheld caller ID is routine, so null is a normal state, and erasing a person must never delete the call record — this row is the retention artefact of record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='scheduling.contact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'location', 'started_at'], name='idx_call_tenant_loc_started'), models.Index(fields=['tenant', 'status'], name='idx_call_tenant_status'), models.Index(fields=['tenant', 'contact'], name='idx_call_tenant_contact')],
            },
        ),
    ]
