# Generated by Django 4.2.30 on 2026-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='transfer',
            field=models.JSONField(default=dict, help_text='{result, reason, destination, initiated_at, duration_seconds, attempts}. `result` and `destination` are the FINAL outcome and the number that produced it. `attempts` is an optional [{destination, result}] list recording each number tried in order — AgentSetting carries a transfer_secondary_number, so "primary rang out, secondary answered" is a designed path, and without this list it could only be narrated in `reason`, where nothing can query it. Empty dict = no transfer was ever attempted, the common case.'),
        ),
    ]
