# Generated by Django 4.2.30 on 2026-07-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_callsession_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='recording_blob',
            field=models.CharField(blank=True, default='', help_text='PRIVATE storage path; "" = no recording. Served only through a short-lived signed URL — never rendered as a src against a public media path. Must not be set without a consent basis in `metadata` — see the comment above.', max_length=512),
        ),
    ]
